FROM ruby:2.5.3

RUN apt-get update -qq && apt-get install -y nodejs
ENV PROJECT_ROOT /usr/src/app
WORKDIR $PROJECT_ROOT
COPY Gemfile $PROJECT_ROOT/Gemfile
COPY Gemfile.lock $PROJECT_ROOT/Gemfile.lock

RUN bundle install
COPY . $PROJECT_ROOT

ENV RAILS_ENV=production

CMD ["rails", "server", "-b", "0.0.0.0"]